sever:
  port: 8080

spring:
  datasource:
    #通用数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bunny?charset=utf8mb4&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  redis:
    database: 0
    host: 192.168.46.128
    port: 6379
    password: 123456
    timeout: 2000
    jedis:
      pool:
        max-active: 10
        max-wait: 3
        max-idle: 10
logging:
  config: classpath:log4j2.xml